### ISSUE TITLE
ApiCheck crashed

### ISSUE THREAD

**Issue by lovemaths** [PMudra/ApiCheck#17]
ApiCheck crashed when I tried to compare two versions (5.2.0-preview, 5.0.0) of [System.IdentityModel.Tokens.Jwt](https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/5.0.0). I am using the code provided in the document. The same code works for other libraries, but not System.IdentityModel.Tokens.Jwt.

```
using (AssemblyLoader assemblyLoader = new AssemblyLoader())
{
    // using the included AssemblyLoader that automatically resolves dependencies
    Assembly devAssembly = assemblyLoader.ReflectionOnlyLoad("path to 5.2.0-preview System.IdentityModel.Tokens.Jwt.dll");
    Assembly refAssembly = assemblyLoader.ReflectionOnlyLoad("path to 5.0.0 version System.IdentityModel.Tokens.Jwt.dll");
    // the comparer configuration specifies the severity levels of the changed API elements and which elements to ignore
    ComparerConfiguration configuration = new ComparerConfiguration();
    // all listed elements are not compared
    configuration.Ignore.Add("Element.To.Be.Ignored");
    // override the default severities
    configuration.Severities.ParameterNameChanged = Severity.Warning;
    configuration.Severities.AssemblyNameChanged = Severity.Hint;
    // easy setup of the ApiChecker using the builder pattern
    ApiComparer.CreateInstance(refAssembly, devAssembly)
                // configure the logging and the comparer 
                .WithComparerConfiguration(configuration)
                .WithDetailLogging(s => Console.WriteLine(s))
                .WithInfoLogging(s => Console.WriteLine(s))
                // write report to desired streams
                .WithHtmlReport(new FileStream("path to report.html", FileMode.Create))
                .Build()     // creating the ApiChecker
                .CheckApi(); // doing the comparison
}
```

The following is the exception I got:

```
[9/18/2017 2:35:59 PM Informational] [xUnit.net 00:00:00.7785350]       System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[9/18/2017 2:35:59 PM Informational] [xUnit.net 00:00:00.7798077]       Stack Trace:
[9/18/2017 2:35:59 PM Informational] [xUnit.net 00:00:00.7802728]            at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
[9/18/2017 2:35:59 PM Informational] [xUnit.net 00:00:00.7806657]            at System.Reflection.RuntimeAssembly.get_DefinedTypes()
[9/18/2017 2:35:59 PM Informational] [xUnit.net 00:00:00.7809789]            at ApiCheck.Comparer.AssemblyComparer.<CompareTypes>b__3_0()
[9/18/2017 2:35:59 PM Informational] [xUnit.net 00:00:00.7812748]            at ApiCheck.Comparer.AssemblyComparer.GetTypeNames(Func`1 getTypes)
[9/18/2017 2:35:59 PM Informational] [xUnit.net 00:00:00.7815510]            at ApiCheck.Comparer.AssemblyComparer.CompareTypes()
[9/18/2017 2:35:59 PM Informational] [xUnit.net 00:00:00.7818108]            at 
ApiCheck.Comparer.AssemblyComparer.Compare()
[9/18/2017 2:35:59 PM Informational] [xUnit.net 00:00:00.7820674]            at ApiCheck.ApiComparer.CheckApi()
[9/18/2017 2:35:59 PM Informational] [xUnit.net 00:00:00.7823240]            at Microsoft.IdentityModel.Tests.Api.RunTest()
```

The following are the assemblies, can you take a look? Thank you!
[assemblies.zip](https://github.com/PMudra/ApiCheck/files/1312385/assemblies.zip)

**Comment by PMudra** [comment]
I reproduced the error on my machine. Unfortunately, the error message is not very useful.
When debugging and viewing the `LoaderExceptions` I get this message:

```
{"Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.":"Microsoft.IdentityModel.Tokens, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}
```

That is because the assembly is not placed in the same directory as `System.IdentityModel.Tokens.Jwt.dll`. All dependencies of the compared assemblies must be present where the `AssemblyLoader` can find them.

Can you please try again with all dependent assemblies in the same directory?

**Comment by lovemaths** [comment]
@PMudra This solves the problem. Thank you very much!
